CREATE DATABASE PembrokePS;
use PembrokePS;

SET default_storage_engine = INNODB;

CREATE TABLE STATUS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  STATUS_NAME varchar (50) NOT NULL,
  HTMLCOLOR varchar (10) Not NULL,
  HTML_Description varchar (20),
  PRIMARY KEY (ID),
  UNIQUE (STATUS_NAME),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE STATUS AUTO_INCREMENT=100;

CREATE TABLE RESULTS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  RESULT_NAME varchar (50) NOT NULL,
  HTMLCOLOR varchar (10) Not NULL,
  HTML_Description varchar (20),
  PRIMARY KEY (ID),
  UNIQUE (RESULT_NAME),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE RESULTS AUTO_INCREMENT=100;

CREATE TABLE PROPERTIES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  PROP_NAME varchar (200) NOT NULL,
  PROP_VALUE varchar (500),
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (PROP_NAME),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ENDPOINT_PORTS
  (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PORT int (11) NOT NULL,
  UNIQUE (PORT),
  ENDPOINT_ASSIGNED_STATUS int (11) NOT NULL,
  ENDPOINT_STATUS int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ENDPOINT_ASSIGNED_STATUS) REFERENCES STATUS (ID),
  FOREIGN KEY (ENDPOINT_STATUS) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE QUEUE_MANAGER_TYPE
(
  ID int (11) NOT NULL AUTO_INCREMENT,
  NAME varchar (255) NOT NULL,
  TABLENAME varchar (255),
  PRIMARY KEY (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE QUEUE_MANAGER
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  QUEUE_MANAGER_TYPE_ID int (11) NOT NULL,
  QMAN_PORT_ID int (11),
  KICKER_PORT_ID int (11),
  STATUS_ID int (11) NOT NULL,
  KICKER_STATUS_ID int (11) NOT NULL,
  WAIT int (11) NOT NULL,
  KICKER_WAIT int (11) NOT NULL,
  HOSTNAME varchar (255),
  IP_ADDRESS varchar (255),
  LOG_FILE varchar (255),
  HEARTBEAT varchar (255),
  KICKER_HEARTBEAT varchar (255),
  QMan_Description varchar (255),
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (KICKER_STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (QMAN_PORT_ID) REFERENCES ENDPOINT_PORTS (ID),
  FOREIGN KEY (KICKER_PORT_ID) REFERENCES ENDPOINT_PORTS (ID),
  FOREIGN KEY (QUEUE_MANAGER_TYPE_ID) REFERENCES QUEUE_MANAGER_TYPE (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORKFLOW_MANAGER_TYPE
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar (255) NOT NULL,
  TABLENAME varchar (255),
  PRIMARY KEY (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORKFLOW_MANAGER
  (
  ID int(11) NOT NULL AUTO_INCREMENT,
  WORKFLOW_MANAGER_TYPE_ID int (11) NOT NULL,
  WKFLW_PORT_ID int (11),
  KICKER_PORT_ID int (11),
  STATUS_ID int (11) NOT NULL,
  KICKER_STATUS_ID int (11) NOT NULL,
  KICKER_WAIT int (11) NOT NULL,
  WAIT int (11) NOT NULL,
  MAX_CONCURRENT_TASKS int (11) NOT NULL,
  HOSTNAME varchar (255),
  IP_ADDRESS varchar (255),  
  LOG_FILE varchar (255),
  HEARTBEAT varchar (255),
  KICKER_HEARTBEAT varchar (255),
  WMan_Description varchar (255),
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (KICKER_STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (WKFLW_PORT_ID) REFERENCES ENDPOINT_PORTS (ID),
  FOREIGN KEY (KICKER_PORT_ID) REFERENCES ENDPOINT_PORTS (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_TYPE_ID) REFERENCES WORKFLOW_MANAGER_TYPE (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PASSWORDS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar (255) NOT NULL,
  PASSWORD varchar (255) NOT NULL,
  PRIMARY KEY (ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TARGET_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar (255) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID), 
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PARENT_TARGET_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  PARENT_TARGET_TYPE_ID int(11) NOT NULL,
  CHILD_TARGET_TYPE_ID int(11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PARENT_TARGET_TYPE_ID) REFERENCES TARGET_TYPES (ID),
  FOREIGN KEY (CHILD_TARGET_TYPE_ID) REFERENCES TARGET_TYPES (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID), 
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

CREATE TABLE SYSTEMS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  SYSTEM_NAME varchar (255) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (SYSTEM_NAME), 
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TARGETS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  TARGET_NAME varchar (255) NOT NULL,
  TARGET_TYPE_ID int (11) NOT NULL,
  IP_ADDRESS varchar (255),
  STATUS_ID int (11) NOT NULL,
  PASSWORD_ID int (11) NOT NULL,
  SYSTEM_ID int (11) NOT NULL,
  Target_Description varchar (255),
  PRIMARY KEY (ID),  
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORDS (ID),
  FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEMS (ID),
  FOREIGN KEY (TARGET_TYPE_ID) REFERENCES TARGET_TYPES (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TASK_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  TASK_NAME varchar (255) NOT NULL,
  TASK_PATH varchar (255) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIORITY int (11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (TASK_NAME), 
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SUBTASK_GENERATOR
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  TASK_TYPE_ID int(11) NOT NULL,
  PASS_SUBTASK_ID int(11)NOT NULL,
  FAIL_SUBTASK_ID int(11)NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (PASS_SUBTASK_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (FAIL_SUBTASK_ID) REFERENCES TASK_TYPES (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE QMAN_TASK_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  QUEUE_MANAGER_TYPE_ID int (11) NOT NULL,
  TASK_TYPE_ID int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (QUEUE_MANAGER_TYPE_ID) REFERENCES QUEUE_MANAGER_TYPE (ID),
  FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WMAN_TASK_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  WORKFLOW_MANAGER_TYPE_ID int (11) NOT NULL,
  TASK_TYPE_ID int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_TYPE_ID) REFERENCES WORKFLOW_MANAGER_TYPE (ID),
  FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TARGET_TASKS_TYPES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  TARGET_TYPE_ID int (11) NOT NULL,
  TASK_TYPE_ID int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  MAX_Retries int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TARGET_TYPE_ID) REFERENCES TARGET_TYPES (ID),
  FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TASKS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  STATUS_ID int (11) NOT NULL,
  RESULT_ID int (11) NOT NULL,
  LOG_FILE varchar (255),
  WORKFLOW_MANAGER_ID int (11),
  TASK_TYPE_ID int (11) NOT NULL,
  TARGET_ID int (11) NOT NULL,
  ARGUMENTS varchar (1000),
  HIDDEN int (11),
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (RESULT_ID) REFERENCES RESULTS (ID),
  FOREIGN KEY (TARGET_ID) REFERENCES TARGETS (ID),
  FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPES (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_ID) REFERENCES WORKFLOW_MANAGER (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PARENT_TASKS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  PARENT_TASK_ID int(11) NOT NULL,
  CHILD_TASK_ID int(11) NOT NULL,
  isRetry int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PARENT_TASK_ID) REFERENCES TASKS (ID),
  FOREIGN KEY (CHILD_TASK_ID) REFERENCES TASKS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

CREATE TABLE MANAGED_FILES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  FILE_NAME varchar (255) NOT NULL,
  FILE_PATH varchar (255) NOT NULL,
  FILE_HASH varchar (255) NOT NULL,
  REBOOT_REQUIRED int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MANAGED_FILE_QM_GROUPS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  MANAGED_FILE_ID int (11) NOT NULL,
  QUEUE_MANAGER_TYPE_ID int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (QUEUE_MANAGER_TYPE_ID) REFERENCES QUEUE_MANAGER_TYPE (ID),
  FOREIGN KEY (MANAGED_FILE_ID) REFERENCES MANAGED_FILES (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MANAGED_FILE_WM_GROUPS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  MANAGED_FILE_ID int (11) NOT NULL,
  WORKFLOW_MANAGER_TYPE_ID int (11) NOT NULL,  
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_TYPE_ID) REFERENCES WORKFLOW_MANAGER_TYPE (ID),
  FOREIGN KEY (MANAGED_FILE_ID) REFERENCES MANAGED_FILES (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE QUEUE_MANAGER_FILES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  QUEUE_MANAGER_ID int (11) NOT NULL,
  MANAGED_FILE_ID int (11) NOT NULL,
  QUEUE_MGR_HASH varchar (255),
  RESULT_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (QUEUE_MANAGER_ID) REFERENCES QUEUE_MANAGER (ID),
  FOREIGN KEY (MANAGED_FILE_ID) REFERENCES MANAGED_FILES (ID),
  FOREIGN KEY (RESULT_ID) REFERENCES RESULTS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORKFLOW_MANAGER_FILES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  WORKFLOW_MANAGER_ID int (11) NOT NULL,
  MANAGED_FILE_ID int (11) NOT NULL,
  WORKFLOW_MGR_HASH varchar (255),
  RESULT_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_ID) REFERENCES WORKFLOW_MANAGER (ID),
  FOREIGN KEY (MANAGED_FILE_ID) REFERENCES MANAGED_FILES (ID),
  FOREIGN KEY (RESULT_ID) REFERENCES RESULTS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ADDITIONAL_PS_MODULES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar (255) NOT NULL,
  GALLERY_NAME varchar (255) NOT NULL,
  MODULE_VERSION varchar (255) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ADDL_MODULES_WMAN_GROUPS
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  ADDL_MODULE_ID int (11) NOT NULL,
  WORKFLOW_MANAGER_TYPE_ID int (11) NOT NULL,
  STATUS_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_TYPE_ID) REFERENCES WORKFLOW_MANAGER_TYPE (ID),  
  FOREIGN KEY (ADDL_MODULE_ID) REFERENCES ADDITIONAL_PS_MODULES (ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORKFLOW_MANAGER_MODULES
(
  ID int(11) NOT NULL AUTO_INCREMENT,
  WORKFLOW_MANAGER_ID int (11) NOT NULL,
  ADDL_MODULE_ID int (11) NOT NULL,
  RESULT_ID int (11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (WORKFLOW_MANAGER_ID) REFERENCES WORKFLOW_MANAGER (ID),
  FOREIGN KEY (ADDL_MODULE_ID) REFERENCES ADDITIONAL_PS_MODULES (ID),
  FOREIGN KEY (RESULT_ID) REFERENCES RESULTS (ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
  

